### ISSUE TITLE
Optional process version in new VDM process behaviors

### ISSUE THREAD

**Issue by Whathecode** [Whathecode/ABC#13]
In commit https://github.com/Whathecode/ABC/commit/42cb47f65803f1544654d6e06cd7298da5253d43 process versions were included into configuration files which should not be specified. Most notably, what lead us to noticing this is the "windows_7.xml" definition, which now targets version 6.1 of 'explorer', using `TargerProcessVersion="6.1"`. This leads to things breaking on Windows 8 since this uses a newer version of explorer.

By default, processes should intentionally target 'any version'. Only when specific version dependencies are known does it make sense to add version number configurations, which then override the 'default' any version. Otherwise, configurations would break at any given update, even though they might still work out of the box. Likewise, a more defined version has precedence over a less defined one.

E.g. given two configuration files, one version 'any' and another version '6.1'. The 'any' configuration file would be used when a version '6.2' is encountered, but when a version '6.1.3' is encountered, the '6.1' configuration should be used.

Also, please change `TargerProcessVersion` to `TargetProcessVersion`.

**Comment by dominkomin** [comment]
"TargetProcessVersion" attribute is optional, in case it is provided, a given setting is used only with a process having the same major version. When "TargetProcessVersion" attribute is set to "any" or is empty, it will be interpreted as "0.0" and used as a general setting. In case more than one general settings is present, one with the higher "Version" attribute will be used.

**Comment by Whathecode** [comment]
Your description does not seem to reflect the requested behavior?

"E.g. given two configuration files, one version 'any' and another version '6.1'. The 'any' configuration file would be used when a version '6.2' is encountered, but when a version '6.1.3' is encountered, the '6.1' configuration should be used."
