### ISSUE TITLE
VDM settings file with empty IgnoreWindows

### ISSUE THREAD

**Issue by Whathecode** [Whathecode/ABC#14]
Currently the VDM manager crashes when VDM settings files are loaded containing `IgnoreWindows` without any containing windows. E.g.: `<IgnoreWindows Mode="AllExcept" />`. The crash occurs since the `Window` collection is set to null, whereas it should simply be loaded as empty instead to prevent null checks all around the place.

The applications need to be running for the crash to occur. The current two settings files including such a collection are `skype.xml` and `spotifyhelper.xml`.

**Comment by dominkomin** [comment]
Issue solved as suggested but please verify- I could not recreate this bug even using two mentioned .xml's. (Maybe problem lays in a different place?)
